name: flutter_night_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  crop_your_image: ^1.0.2
  flutter:
    sdk: flutter
  flutter_deck: ^0.12.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  gap: ^3.0.1
  intl: ^0.18.1
  riverpod_annotation: ^2.3.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  generate: true
